name: Splunk Appinspect
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths:
      - "SA-CrowdstrikeDevices/**"
    types: [opened, ready_for_review]

jobs:
  call-packaging-workflow:
    uses: ZachTheSplunker/app-wfa/.github/workflows/appinspect.yml@main
    with:
      package-name: SA-CrowdstrikeDevices
    secrets:
      API_USER: ${{ secrets.API_USER }}
      API_PASS: ${{ secrets.API_PASS }}
